const categories = [
  { name: 'Microsoft Word', icon: 'mdi-file-word', boxIcon: 'mdi-file-word-box', ext: /\.docx$/, mime: /application\/vnd.openxmlformats-officedocument.wordprocessingml.document/ },
  { name: 'Microsoft Word', icon: 'mdi-file-word', boxIcon: 'mdi-file-word-box', ext: /\.doc$/, mime: /application\/msword/ },
  { name: 'Microsoft Excel', icon: 'mdi-file-excel', boxIcon: 'mdi-file-excel-box', ext: /\.xlsx$/, mime: /application\/vnd.openxmlformats-officedocument.spreadsheetml.sheet/ },
  { name: 'Microsoft Excel', icon: 'mdi-file-excel', boxIcon: 'mdi-file-excel-box', ext: /\.xls$/, mime: /application\/vnd.ms-excel/ },
  { name: 'Rich Text Format', icon: 'mdi-file-word', boxIcon: 'mdi-file-word-box', ext: /\.rtf$/, mime: /application\/rtf/ },
  { name: 'Adobe Portable Document Format', icon: 'mdi-file-document', boxIcon: 'mdi-file-pdf-box', ext: /\.pdf$/, mime: /application\/pdf/ },
  { name: 'Microsoft PowerPoint', icon: 'mdi-file-powerpoint', boxIcon: 'mdi-file-powerpoint-box', ext: /\.pptx$/, mime: /application\/vnd.openxmlformats-officedocument.presentationml.presentation/ },
  { name: 'Microsoft PowerPoint', icon: 'mdi-file-powerpoint', boxIcon: 'mdi-file-powerpoint-box', ext: /\.ppt$/, mime: /application\/vnd.ms-powerpoint/ },
  { name: 'Email', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-email-box', ext: /\.eml$/, mime: /message\/rfc822/ },
  { name: 'JPEG images', icon: 'mdi-file-image', boxIcon: 'mdi-file-jpg-box', ext: /\.jpe?g$/, mime: /image\/jpeg/ },
  { name: 'Portable Network Graphics', icon: 'mdi-file-image', boxIcon: 'mdi-file-png-box', ext: /\.png$/, mime: /image\/png/ },
  { name: 'Scalable Vector Graphics', icon: 'mdi-file-image', boxIcon: 'mdi-file-xml-box', ext: /\.svg$/, mime: /image\/svg+xml/ },
  { name: 'Graphics Interchange Format', icon: 'mdi-file-image', boxIcon: 'mdi-file-gif-box', ext: /\.gif$/, mime: /image\/gif/ },
  { name: 'Tagged Image File Format', icon: 'mdi-file-image', boxIcon: 'mdi-drawing-box', ext: /\.tiff?$/, mime: /image\/tiff/ },
  { name: 'Icon format', icon: 'mdi-file-image', boxIcon: 'mdi-drawing-box', ext: /\.ico$/, mime: /image\/vnd.microsoft.icon/ },
  { name: 'Windows OS/2 Bitmap Graphics', icon: 'mdi-file-image', boxIcon: 'mdi-drawing-box', ext: /\.bmp$/, mime: /image\/bmp/ },
  { name: 'Comma-separated values', icon: 'mdi-file-delimited', boxIcon: 'mdi-file-table-box', ext: /\.csv$/, mime: /text\/[ct]sv/ },
  { name: 'Text', icon: 'mdi-file-document', boxIcon: 'mdi-text-box', ext: /\.txt$/, mime: /text\/plain/ },
  { name: 'OpenDocument presentation document', icon: 'mdi-file-powerpoint', boxIcon: 'mdi-file-powerpoint-box', ext: /\.odp$/, mime: /application\/vnd.oasis.opendocument.presentation/ },
  { name: 'OpenDocument spreadsheet document', icon: 'mdi-file-excel', boxIcon: 'mdi-file-excel-box', ext: /\.ods$/, mime: /application\/vnd.oasis.opendocument.spreadsheet/ },
  { name: 'OpenDocument text document', icon: 'mdi-file-word', boxIcon: 'mdi-file-word-box', ext: /\.odt$/, mime: /application\/vnd.oasis.opendocument.text/ },
  { name: 'XML', icon: 'mdi-file-code', boxIcon: 'mdi-file-xml-box', ext: /\.xml$/, mime: /application\/xml|text\/xml/ },
  { name: 'JSON format', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.json$/, mime: /application\/json/ },
  { name: 'JSON-LD format', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.jsonld$/, mime: /application\/ld+json/ },
  { name: 'ZIP archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.zip$/, mime: /application\/zip/ },
  { name: 'BZip2 archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.bz2$/, mime: /application\/x-bzip2/ },
  { name: 'BZip archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.bz$/, mime: /application\/x-bzip/ },
  { name: 'RAR archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.rar$/, mime: /application\/vnd.rar/ },
  { name: '7-zip archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.7z$/, mime: /application\/x-7z-compressed/ },
  { name: 'Tape Archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.tar$/, mime: /application\/x-tar/ },
  { name: 'GZip Compressed Archive', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.gz$/, mime: /application\/gzip/ },
  { name: 'Archive document', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.arc$/, mime: /application\/x-freearc/ },
  { name: 'XHTML', icon: 'mdi-file-document', boxIcon: 'mdi-text-box', ext: /\.xhtml$/, mime: /application\/xhtml+xml/ },
  { name: 'Microsoft Visio', icon: 'mdi-file-powerpoint', boxIcon: 'mdi-file-powerpoint-box', ext: /\.vsd$/, mime: /application\/vnd.visio/ },
  { name: 'WEBM audio', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.weba$/, mime: /audio\/webm/ },
  { name: 'WEBM video', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.webm$/, mime: /video\/webm/ },
  { name: 'WEBP image', icon: 'mdi-file-image', boxIcon: 'mdi-drawing-box', ext: /\.webp$/, mime: /image\/webp/ },
  { name: 'HyperText Markup Language', icon: 'mdi-file-document', boxIcon: 'mdi-web-box', ext: /\.html?$/, mime: /text\/html/ },
  { name: 'Cascading Style Sheets', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.css$/, mime: /text\/css/ },
  { name: 'Electronic publication', icon: 'mdi-file-document', boxIcon: 'mdi-alpha-e-box', ext: /\.epub$/, mime: /application\/epub+zip/ },
  { name: 'AAC audio', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.aac$/, mime: /audio\/aac/ },
  { name: 'AbiWord document', icon: 'mdi-file-word', boxIcon: 'mdi-file-word-box', ext: /\.abw$/, mime: /application\/x-abiword/ },
  { name: 'AVIF image', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.avif$/, mime: /image\/avif/ },
  { name: 'AVI: Audio Video Interleave', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.avi$/, mime: /video\/x-msvideo/ },
  { name: 'Amazon Kindle eBook format', icon: 'mdi-file-document', boxIcon: 'mdi-alpha-k-box', ext: /\.azw$/, mime: /application\/vnd.amazon.ebook/ },
  { name: 'Any kind of binary data', icon: 'mdi-file-document', boxIcon: 'mdi-checkbox-blank', ext: /\.bin$/, mime: /application\/octet-stream/ },
  { name: 'CD audio', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.cda$/, mime: /application\/x-cdf/ },
  { name: 'C-Shell script', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.csh$/, mime: /application\/x-csh/ },
  { name: 'MS Embedded OpenType fonts', icon: 'mdi-file-code', boxIcon: 'mdi-alpha-t-box', ext: /\.eot$/, mime: /application\/vnd.ms-fontobject/ },
  { name: 'iCalendar format', icon: 'mdi-file-code', boxIcon: 'mdi-file-xml-box', ext: /\.ics$/, mime: /text\/calendar/ },
  { name: 'Java Archive (JAR)', icon: 'mdi-file-document-multiple', boxIcon: 'mdi-zip-box', ext: /\.jar$/, mime: /application\/java-archive/ },
  { name: 'JavaScript', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.js$/, mime: /text\/javascript/ },
  { name: 'MP3 audio', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.mp3$/, mime: /audio\/mpeg/ },
  { name: 'MP4 video', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.mp4$/, mime: /video\/mp4/ },
  { name: 'MPEG Video', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.mpeg$/, mime: /video\/mpeg/ },
  { name: 'Apple Installer Package', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.mpkg$/, mime: /application\/vnd.apple.installer+xml/ },
  { name: 'OGG audio', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.oga$/, mime: /audio\/ogg/ },
  { name: 'OGG video', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.ogv$/, mime: /video\/ogg/ },
  { name: 'OGG', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.ogx$/, mime: /application\/ogg/ },
  { name: 'Musical Instrument Digital Interface', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.midi?$/, mime: /audio\/midi|audio\/x-midi/ },
  { name: 'Waveform Audio Format', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.wav$/, mime: /audio\/wav/ },
  { name: 'JavaScript module', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.mjs$/, mime: /text\/javascript/ },
  { name: 'Opus audio', icon: 'mdi-file-music', boxIcon: 'mdi-music-box', ext: /\.opus$/, mime: /audio\/opus/ },
  { name: 'OpenType font', icon: 'mdi-file-code', boxIcon: 'mdi-alpha-t-box', ext: /\.otf$/, mime: /font\/otf/ },
  { name: 'Hypertext Preprocessor (Personal Home Page)', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.php$/, mime: /application\/x-httpd-php/ },
  { name: 'Bourne shell script', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.sh$/, mime: /application\/x-sh/ },
  { name: 'MPEG transport stream', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.ts$/, mime: /video\/mp2t/ },
  { name: 'TrueType Font', icon: 'mdi-file-code', boxIcon: 'mdi-alpha-t-box', ext: /\.ttf$/, mime: /font\/ttf/ },
  { name: 'Web Open Font Format (WOFF)', icon: 'mdi-file-code', boxIcon: 'mdi-alpha-w-box', ext: /\.woff2$/, mime: /font\/woff2/ },
  { name: 'Web Open Font Format (WOFF)', icon: 'mdi-file-code', boxIcon: 'mdi-alpha-w-box', ext: /\.woff$/, mime: /font\/woff/ },
  { name: 'XUL', icon: 'mdi-file-code', boxIcon: 'mdi-code-braces-box', ext: /\.xul$/, mime: /application\/vnd.mozilla.xul+xml/ },
  { name: '3GPP2 udio/video container', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.3g2$/, mime: /video\/3gpp2/ },
  { name: '3GPP audio/video container', icon: 'mdi-file-video', boxIcon: 'mdi-play-box', ext: /\.3gp$/, mime: /video\/3gpp/ },
]

export const getFileCategory = file => {
  for (let category of categories) {
    if (file.mimetype && file.mimetype.match(category.mime)) return category.name
    if (file.name && file.name.match(category.ext)) return category.name
  }
  return 'File of undefined type'
}
